### ISSUE TITLE
Could not initialize class co.elastic.apm.mule4.agent.ApmHandler

### ISSUE THREAD

**Issue by GoBenGoh** [michaelhyatt/elastic-apm-mule4-agent#16]
![image](https://user-images.githubusercontent.com/76719511/143796212-4a3f9213-6f72-4b3f-b7ec-dff51b94063c.png)
I've managed to get a build success when installing the agent and my mule app is working correctly but I get this error. Is there something wrong with my dependencies?
![image](https://user-images.githubusercontent.com/76719511/143796360-8aaf5f64-ba8a-4985-b54c-92335d909eeb.png)

**Comment by GoBenGoh** [comment]
Full line:
INFO  2021-11-29 14:37:55,847 [[MuleRuntime].uber.03: [diy1-1].usernameFlow.CPU_LITE @6ba55b6f] [processor: usernameFlow/processors/3; event: f9b8dca0-50b4-11ec-a5d1-dc1ba166b542] org.mule.runtime.core.internal.context.notification.Policy: NotificationListener co.elastic.apm.mule4.agent.ApmMessageProcessorNotificationListener$$EnhancerByCGLIB$$d5037dd4@3eb86072 was unable to fire notification MessageProcessorNotification{action=message processor post invoke, processor=usernameFlow/processors/3, resourceId=usernameFlow, serverId=DESKTOP-4D106F7..diy1-1, timestamp=1638149875847} due to an exception: java.lang.NoClassDefFoundError: Could not initialize class co.elastic.apm.mule4.agent.ApmHandler.

**Comment by michaelhyatt** [comment]
@GoBenGoh can you please try without the `apm-agent-attach` dependency? The agent should include all the needed dependencies. Check out the `examples` directory for `pom.xml` file configs. You can also download the jars from the releases, so you don't have to build them yourself.

**Comment by GoBenGoh** [comment]
apm-agent-attach dependency is required otherwise my app fails to deploy (Cannot load class 'co.elastic.apm.attach.ElasticApmAttacher'). 
I downloaded the release jar (0.4.0) and ran the command filling out the path to jar and version as per the instructions
![image](https://user-images.githubusercontent.com/76719511/144300826-9876391a-8518-4a93-830d-c36deb7d467d.png)

**Comment by GoBenGoh** [comment]
Actually the guy from this thread fixed it: https://github.com/michaelhyatt/elastic-apm-mule4-agent/issues/13

I needed to add this to my pom 
`<dependency>`
    `<groupId>co.elastic.apm</groupId>`
    `<artifactId>apm-agent-api</artifactId>`
    `<version>1.21.0</version>`
`</dependency>`
