### ISSUE TITLE
it dosent work with mule 4.6.2

### ISSUE THREAD

**Issue by holiday-sunrise** [michaelhyatt/elastic-apm-mule4-agent#24]
we try to use it with mule 4.6.2 but it dosent work

**Comment by holiday-sunrise** [comment]
`│ echo-dapi {"@timestamp":"2024-06-07T12:16:04.323Z","log.level": "INFO","message":"NotificationListener co.elastic.apm.mule4.agent.ApmMessageProcessorNotificationListener$ByteBuddy$6yz6CH9Y@689dea8d; location: (null) was unable to fire notification MessageProcessorNotification{action=message processor pre invoke, processor=echo-dapi-main/processors/1, resourceI │
│ d=echo-dapi-main, serverId=echo-dapi-c5d6dbb94-gvpkl..echo-dapi-mule-application, timestamp=1717762564187} due to an exception: java.lang.NullPointerException.", "ecs.version": "1.2.0","service.name":"echo-dapi","service.version":"1.0.3","event.dataset":"echo-dapi","process.thread.name":"[MuleRuntime].uber.09: [echo-dapi-mule-application].echo-dapi-main.CPU_LI │
│ TE @f166cf","log.logger":"org.mule.runtime.core.internal.context.notification.Policy","correlationId":"b5f0e550-24c7-11ef-a492-deace84a50fb","processorPath":"echo-dapi-main/processors/1"}  `

**Comment by holiday-sunrise** [comment]
[echo-dapi.zip](https://github.com/user-attachments/files/15739117/echo-dapi.zip)

**Comment by michaelhyatt** [comment]
I stopped working on it and it has never been tested with Mule 4.6. There is a better agent that supports OTel, so I suggest to use that one since Elastic understands OTel.

**Comment by holiday-sunrise** [comment]
When you stopped working on this Projekt you should archive it. :-) Thx for your feedback wie will try Otel.

**Comment by holiday-sunrise** [comment]
close the case
